### PR TITLE
Updating NWS8 and adding upgrades from Wang et. al. (2022)

### PR DESCRIPTION
**Pull request by cblakely97**
- Changing the value of omega used in HollandGet to match the value in adc_constants module
- Eliminating the calculation of coriolis frequency from HollandGet and instead uses CORIF found in mesh module
- Moving multiplication by boundary layer adjustment factor (BLADj) to occur after background wind field is applied
- Moving conversion from one minute average to ten minute average multiplication to after background wind field is added
- Moving initialization code formerly found in HollandGet and GetHollandStormData into NWS8INIT to make the code more readable
- Adding the nws8Control namelist. This namelist contains the following options (D denotes default):
   - vortexModel = "Holland" (D) or "CLE15" - Incorporates work done in Wang et. al. (2022) that allows for the use an alternative vortex model
   - backgroundWindModel = "radialVelocityWeighted" (D) or "LC12"
      - Incorporates work done in Wang et. al. (2022) that allows for an alternative background wind model
   - BCalc = "limited" (D) or "exact" 
       - "limited" is original ADCIRC where the Holland B parameter is calculated once for each time step and limited to 'reasonable' values 
       - "exact" calculates Holland B for each individual node and does not limit the range of the value
   - thetaLatDep = .false. (D) or .true.
      - Original ADCIRC did not include the latitude dependency in calculating distance from the center of the storm. This option preserves legacy behavior while also allowing for more accurate calculation of distances
   - useInflow = .false. (D) or .true. 
       - Original adcirc assumed an inflow angle of 0 degrees. This allows it to be calculated based on velocity
   - w_cool = 2.0 (D) or any value
      - Only used in CLE15 model. This is the magnitude of the radiative-subsidence rate in the free troposphere
   - CkCd_calc = .false. (D) or .true. 
      - Only used in CLE15 model. CkCd is the ratio of exchange coefficients of enthalpy and momentum. If this is false then a constant value is used. If true then CkCd is calculated from the parametric relationship:
         - CkCd = 0.00055*Vmax^2 - 0.0259*Vmax + 0.763 (see Chavas et. al. (2015))
   - CkCd = 1.0 (D) or any value 
       - if CkCd_calc = .false. then this is the value used for CkCd when calculating the CLE15 wind profile

References:

Chavas, D. R., Lin, N., & Emanuel, K. (2015). A Model for the Complete Radial Structure of the Tropical Cyclone Wind Field. Part I: Comparison with Observed Structure. Journal of the Atmospheric Science, 72(9), 3647-3662. https://doi.org/10.1175/JAS-D-15-0014.1

Wang, Shuai, Ning Lin, and Avantika Gori. “Investigation of Tropical Cyclone Wind Models With Application to Storm Tide Simulations.” Journal of Geophysical Research: Atmospheres 127, no. 17 (2022): e2021JD036359. https://doi.org/10.1029/2021JD036359.

# Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Bug fix with breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Update to existing feature to add new functionality
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (feature that would cause existing functionality to not work as expected)

# Issue Number

# How Has This Been Tested?

# Relevant Publications (if applicable)

Chavas, D. R., Lin, N., & Emanuel, K. (2015). A Model for the Complete Radial Structure of the Tropical Cyclone Wind Field. Part I: Comparison with Observed Structure. Journal of the Atmospheric Science, 72(9), 3647-3662. https://doi.org/10.1175/JAS-D-15-0014.1

Chavas, D. R., & Lin, N. (2016). A Model for the Complete Radial Structure of the Tropical Cyclone Wind Field. Part II: Wind Field Variability. Journal of the Atmospheric Sciences, 73(8), 3093-3113. https://doi.org/10.1175/JAS-D-15-0185.1

Lin, N., and D. Chavas (2012), On hurricane parametric wind and applications in storm surge modeling, J. Geophys. Res., 117, D09120, doi:[10.1029/2011JD017126](https://doi.org/10.1029/2011JD017126).

Wang, Shuai, Ning Lin, and Avantika Gori. “Investigation of Tropical Cyclone Wind Models With Application to Storm Tide Simulations.” Journal of Geophysical Research: Atmospheres 127, no. 17 (2022): e2021JD036359. https://doi.org/10.1029/2021JD036359.

Wang, S., N. Lin, A. Gori. (2022) "New wind forcing option (CLE15 wind model) for hurricane surge simulation with ADCIRC." DesignSafe-CI. https://doi.org/10.17603/ds2-xd0r-bk81 v1 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [x] My code is up-to-date and tested with changes from the latest version of `main`

## If any of the above are not checked, please explain why:

# Further comments

This pull request incorporates the upgrades to NWS = 8 found in Wang et. al., (2022) into the main version of ADCIRC. Formerly, this capability was only found in the DesignSafe repository and required the use of cmake compiler flags to enable the CLE15 and LC12 vortex and background winds. This commit instead moves activation to a namelist that preserves legacy behavior by default.

### CODE REVIEW

**Comment by Jiangchao3** [comment]
Hi @cblakely97, thanks for adding the CLE15 wind model into the main adcirc, I want to use it but i don't knwo which version of adcirc shoul use. I find CLE15 model in your cle15_lc12 branch [https://github.com/cblakely97/adcirc/blob/cle15_lc12/src/wind.F](url), and notice that you complete some test here [https://github.com/cblakely97/adcirc-testsuite/tree/v56/adcirc/adcirc_irene_cle15_lc12-parallel](url), but I don't find it in the latest main adcirv version [https://github.com/adcirc/adcirc/blob/main/src/wind.F](url). 

I am wondering is the CLE15 model is ready to use and how can I use it correctly? I am looking forward to your help and kind reply. Many thanks. 

Jiangchao

**Comment by cblakely97** [comment]
Hi @Jiangchao3,

I am still working with the other developers to get the CLE15 model into the main ADCIRC branch but haven't had time to finalize the pull request. The capability can be found on my branch at https://github.com/cblakely97/adcirc/tree/cle15_lc12 and can be accessed that way. In the next couple of weeks I will finalize this pull request and work on getting it merged into the main branch. The cle14_lc12 branch that I linked above passes the entire test-suite, so it should be ok to use but note that it is not fully up to date with the main branch (one of the things I need to do before I can finalize the pull request).

Coleman

**Comment by Jiangchao3** [comment]
@cblakely97 Thanks for your timely reply, I will start to try your cle15_lc12 branch first and wait for your finish the merge. 

Jiangchao

**Comment by Jiangchao3** [comment]
Hi, @cblakely97, today i just try to build/make the cel15_lc12/adcirc by cmake, but failed, I post the error here for your information. I don't know what's wrong with it, but hope the issues could be fixed in your next merge version.

image

**Pull request closed without merging**
