### PR TITLE
Store H1 and H2 to fix Subgrid Barriers

### PR DESCRIPTION
**Pull request by dylnwood**
# Description

Add the global variables H1 and H2 to save the flow depth at the previous and current timesteps.

These updates were primarily developed to resolve an issue with subgrid barriers, whereby the wrong value of H1 (computed as the bathymetric depth plus the previous surface elevation at the node, DP + ETA1) was obtained when changing DP on the current timestep. In some cases, if DP is changed at a subgrid barrier, the value of H1 could become zero (even though the depth was not zero at the previous timestep, e.g., for very shallow flows), which leads to infinite wind stress in the momentum solver (since H1 is in the denominator of the formula for computing wind stress). The wind limiter code, for wind stress in very shallow water, then converts this Infinity into a NaN, which thereby leads to NaNs in the velocity solutions. This subsequently causes the elevation solution to become non-physical on the next timestep and onwards, although the model does not crash until the elevation error level is exceeded.

The NOAA team first encountered this problem around 1/5/2024 on the Global STOFS grid in their 7 day storm surge forecasts, and then the UND team encountered the same issue on 1/10/2024 in their own 7 day storm surge forecast using Global STOFS. The issue was eventually traced to NaNs in the velocity solution, originating at the location of a subgrid barrier near the coast of North Carolina.

To avoid improperly computing H1 after changing DP, we simply introduce the global variables H1 and H2 to store the values of the depths, and we then retrieve these values as needed. This slightly reduces the model's compute load, while slightly raising the memory load, since we no longer have to recompute the depths as frequently, e.g., DP + ETAX. The time varying bathymetry feature also suffers from this same issue, since the variables DP1 and DP2 are not used in either governing equations solver, so this update should also improve results from using that feature, and it should be compatible with any future updates that modify the DP variable.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Bug fix with breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Update to existing feature to add new functionality
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (feature that would cause existing functionality to not work as expected)

# Issue Number

https://github.com/noaa-ocs-modeling/STOFS-2D-Global-Operation/issues/66#issuecomment-1904245083

# How Has This Been Tested?

We tested on the Global-STOFS 2D mesh over several days of hindcasting/forecasting during the first two weeks in January with forcing by 1-hourly GFS winds, ice cover and tidal potentials (major 8 constituents).  We added some debugging code (now removed) to track down a NaN in the velocity solution originating at the location of a subgrid barrier on the US east coast. We discovered that when a subgrid barrier is overtopped, but the elevation is low enough at the barrier to cause a reset, i.e., when DP + ETA < HABSMIN and the elevation is raised so that ETA = HABSMIN - DP, then the bathy at the subgrid barrier could be raised by the same amount (or more) in the "applySubgridBarrier" routine. Therefore, when computing the depth at the previous timestep, H1 = DP + ETA1, since we no longer are using the value of DP at the previous timestep, a non-physical value could be obtained, either zero or negative, leading to the observed NaN in the velocity solution (when H1 = 0).

After tracking down the source of the issue, the global variables H1 and H2 were added to the code to save the depths at the previous and current timesteps, respectively. We attempted the error run in a few ways to test these code changes. First, we repeated the simulation without the code changes, but also without subgrid barriers, i.e., by removing the nodal attribute from the fort.15 file, to confirm this feature as the source of the issue, and we did not encounter any NaNs or error levels in the elevations/velocities. Next, we added the updated code (i.e., using the global variables H1 and H2) and repeated the simulation, again with no subgrid barriers, to ensure that the new code did not lead to any unexpected behavior when the subgrid barrier feature is not used. Again, no errors were encountered. Finally, we repeated the simulation with the new code as well as with the subgrid barriers, and again, found no errors.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [x] My code is up-to-date and tested with changes from the latest version of `main`

## If any of the above are not checked, please explain why:

I have *not* made corresponding changes to the documentation, because I don't think any relevant documentation exists with respect to this issue.

I have *not* added new tests that prove my fix is effective or that my feature works. So far all of the existing tests are sufficient.

# Further comments

We considered using the existing global variables DP1 and DP2 that are used by the time-varying bathymetry feature, as opposed to bringing in the new global variables H1 and H2, however, we figured that it would be more straightforward to save the values of H1 and H2, rather than recompute them at each timestep, so that the changes could be applicable towards both the subgrid barrier and time-varying bathymetry features, without having to modify the code for either, as well as (hopefully) towards any other future updates on DP that may be integrated into the code.

### CODE REVIEW

**Comment by dylnwood** [comment]
These changes are the same as those merged recently into the `noaa` branch by the pull request here:
[Fixes for NOAA Version of Code -- Velcheck and store H1 and H2 to fix Subgrid Barriers](https://github.com/adcirc/adcirc/pull/370)

However, this update does not include the new "velcheck" code feature -- only the fix for subgrid barriers.

**Comment by zcobell** [comment]
Thanks @dylnwood. How does this square with the method @chrismassey put in place for his time varying bathymetry? Would these conflict or could they be brought together? https://github.com/adcirc/adcirc/blob/aedcbd9aa05cb67c57da990d7535c7220ab0cd9b/src/timestep.F#L456

**Comment by dylnwood** [comment]
> Thanks @dylnwood. How does this square with the method @chrismassey put in place for his time varying bathymetry? Would these conflict or could they be brought together?
> 
> https://github.com/adcirc/adcirc/blob/aedcbd9aa05cb67c57da990d7535c7220ab0cd9b/src/timestep.F#L456
Hi @zcobell!

Seems to me that there should be no conflict and that the updated code should interface seamlessly with the time-varying bathy, especially since the update on H2 happens after the bit of code in question. We may need to test this out some more, but from my own review, I can't see why they wouldn't work together.

**Comment by dylnwood** [comment]
Hi @zcobell! We actually touched on this a bit this morning in our call with NOAA. I think you're onto something, since yes, on the first step of a hot start, the best we can do for now is assume that H1 = H2, which may perturb the solution a bit.

Because of this, I also think it may be a good idea to save H1 and H2 in the hot start file. What do you think @dwirasae?

**Comment by dwirasae** [comment]
Hello Zach and Dylan,

That is what I was thinking (but was hoping that no one brings it up :-)).
Anyway, I think it is certainly a good idea to record H1 and H2 in the hot
start file. We will need to make sure that the implementation does not
break a hor strat run with the binary hot start file format. Anyway, let me
know what you guys think.

Best,
Dam

**Comment by zcobell** [comment]
My opinion is that if we need to break the binary hot start file, an integer release version is the time to do it so we can ensure things are done correctly. The netCDF based hot starts are much more flexible, but ultimately it would be best to get this right and keep things consistent between the formats. If we agree that we're following semantic versioning, integer releases do not guarantee API compatibility, and so we'd be justified in making this change.

**Comment by dwirasae** [comment]
I agree with making this integer release.

**Comment by tgasher** [comment]
Would this mean that a binary hotstart file is no longer fully supported?  As a corollary, I assume this is the first feature not supported by binary hotstarts.  This is a major decision, since it makes netCDF semi-mandatory.  It's not possible to include this info in the binary hotstart?

**Comment by zcobell** [comment]
Just the opposite - this information would be added to the binary hotstart, however pre-v56 binary hot starts would not be compatible with v56

**Pull request merged**
